name: Docker

on:
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest

    name: Update Docker description

    steps:
      - uses: actions/checkout@v2

      - name: Update description on Dockerhub
        uses: ms-jpq/sync-dockerhub-readme@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: kamaradcoal/minecraft-forge
          readme: "./README.md"
