name: Docker Commit

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  push:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        minecraft:
          - 1.16.5
          - 1.16.4
          - 1.15.2
          - 1.14.4
          - 1.13.2
          - 1.12.2
          - 1.11.2
          - 1.10.2
          - 1.9.4
          - 1.8.9
        include:
          - minecraft: 1.16.5
            forge: 1.16.5-36.1.0
          - minecraft: 1.16.4
            forge: 1.16.4-35.1.4
          - minecraft: 1.15.2
            forge: 1.15.2-31.2.0
          - minecraft: 1.14.4
            forge: 1.14.4-28.2.0
          - minecraft: 1.13.2
            forge: 1.13.2-25.0.219
          - minecraft: 1.12.2
            forge: 1.12.2-14.23.5.2854
          - minecraft: 1.11.2
            forge: 1.11.2-13.20.1.2386
          - minecraft: 1.10.2
            forge: 1.10.2-12.18.3.2185
          - minecraft: 1.9.4
            forge: 1.9.4-12.17.0.1976
          - minecraft: 1.8.9
            forge: 1.8.9-11.15.1.1722

    name: Tag Commit for MC ${{ matrix.minecraft }} & Forge ${{ matrix.forge }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Build and push
        id: docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: quay.io/kamaradcoal/minecraft-forge:${{ matrix.forge }}-${{ github.sha }}
          build-args: |
            MINECRAFT_VERSION=${{ matrix.minecraft }}
            FORGE_VERSION=${{ matrix.forge }}
